export const skillsList = [
    "HTML",
    "JavaScript",
    "JS Immutability",
    "CSS BEM convention",
    "CSS Flexbox",
    "CSS Grid",
    "React",
    "React-Redux",
    "React-Saga",
    "React Hooks",
    "styled-components",
    "Working with API (fetch, axios)",
    "Error handling",
    "NPM",
    "Git",
    "GitHub Pull Requests & Reviews",
    "Teamwork",
    "Scrum basics",
    "Selling and negotiations skills",
    "Trello",
    "Web Design",
    "Adobe Photoshop (Basic knowledge)",
    "Adobe Illustrator (Basic knowledge)",
    "Figma (Basic knowledge)",
    "Communicative English language",
  ];

  export const toLearnList = [
      "TypeScript",
      "React Native",
      "Angular",
      "Mastering Illustrator",
      "Mastering Figma",
      "한국어 (Korean language)",
  ];